name: docs_pages_workflow
on:
  push:
    branches: [fix-doc]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    container: python:slim-buster
    steps:
      # - name: Prereqs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     apt-get update
      #     apt-get install -y git gcc
      #     git clone --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
      #   shell: bash
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v1
      - name: Execute script to build our documentation and update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install -y git gcc virtualenv make git rsync python3-pip python3-sphinx python3-sphinx-rtd-theme
          git clone --branch fix-doc --depth 1 "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
          pwd
          ls -lah
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
          python3 -m venv ./venv
          pip3 install -r requirements-dev.txt
          python3 setup.py develop
          source venv/bin/activate
          make -C docs clean
          make -C docs html
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          docroot=`mktemp -d`
          rsync -av "docs/_build/html/" "${docroot}/"
          pushd "${docroot}"
          git init
          git remote add deploy "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b gh-pages
          touch .nojekyll
          cat > README.md <<EOF
          # GitHub Pages Cache

          Nothing to see here. The contents of this branch are essentially a cache that's not intended to be viewed on github.com.


          If you're looking to update our documentation, check the relevant development branch's 'docs/' dir.
          EOF
          git add .
          msg="Updating Docs for commit ${GITHUB_SHA} made on `date -d"@${SOURCE_DATE_EPOCH}" --iso-8601=seconds` from ${GITHUB_REF} by ${GITHUB_ACTOR}"
          git commit -am "${msg}"
          git push deploy gh-pages --force
          popd
          exit 0
        shell: bash
# ./docs/buildDocs.sh
